name: GitHub Actions Build formatter
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install
      - run: npm run start

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.1.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@v1.3.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          head-ref: ${{steps.create_tag.outputs.version}}
          filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        if: steps.create_tag.outputs.successful
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.version }}
          release_name: ${{ steps.create_tag.outputs.version }}
          body: |
            [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/code-example@${{steps.create_tag.outputs.versionNumber}}/file/README.md) [![](https://img.shields.io/github/issues/jaywcjlove/code-example.svg)](https://github.com/jaywcjlove/code-example/releases) [![](https://img.shields.io/github/forks/jaywcjlove/code-example.svg)](https://github.com/jaywcjlove/code-example/network) [![](https://img.shields.io/github/stars/jaywcjlove/code-example.svg)](https://github.com/jaywcjlove/code-example/stargazers) [![](https://img.shields.io/github/release/jaywcjlove/code-example.svg)](https://github.com/jaywcjlove/code-example/releases)

            ${{ steps.changelog.outputs.compareurl }}
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}